# Generated by Django 3.2.6 on 2021-08-03 05:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.DeleteModel(
            name='page',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
