# Generated by Django 3.2.6 on 2021-08-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_auto_20210803_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
