# Generated by Django 3.2.6 on 2021-08-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_auto_20210803_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('number', models.IntegerField()),
                ('Question', models.CharField(max_length=200)),
                ('Answer', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('True', 'True'), ('false', 'false')], max_length=10)),
            ],
        ),
    ]
